apiVersion: v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pg-admin
    env: prod
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
      metadata:
        labels:
          app: odoo
      spec:
        containers:
          - image: dpage/pgadmin4
            name: pg-amdin
            env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: pgadmin@pgadmin.com
            - name: PGADMIN-DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-admin
                  key: PGADMIN_DEFAULT_PASSWORD
            ports:
            - containerPort: 5050
              name: postgres
            volumeMounts:
            - name: pg-admin-server
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
            - name: pg-amdin-data
              moutPath: /var/lib/pgadmin
          volumes:
          - name: pg-admin-server
            configMap:
              name: pgadmin-config
              items:
              - key: servers.json
                path: servers.json
          - name: pg-admin-data
            persistentVolumeClaim:
              claimName: pgadmin-pvc
